# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
---
version: 2
project_name: "cost-exporter"

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos: ["linux", "darwin"]
    goarch: ["amd64", "arm64"]
    goamd64: ["v2"]
    goarm: ["6", "7"]
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: arm
        goarm: 7
      - goarm: mips64
      - gomips: hardfloat
      - goamd64: v4

sboms:
  - artifacts: archive

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

dockers:
  - id: cost-exporter-amd64
    use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    goamd64: "v2"
    image_templates: ["grem1in/{{ .ProjectName }}:{{ .Version }}-amd64"]
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/grem11n/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/grem11n/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=APACHE
  - id: cost-exporter-arm64
    use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64
    goarm: 8
    image_templates: ["grem1in/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/grem11n/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/grem11n/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=APACHE
# Create and push Docker multi-platform images
docker_manifests:
  - name_template: grem1in/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - grem1in/{{ .ProjectName }}:{{ .Version }}-amd64
      - grem1in/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: grem1in/{{ .ProjectName }}:latest
    image_templates:
      - grem1in/{{ .ProjectName }}:{{ .Version }}-amd64
      - grem1in/{{ .ProjectName }}:{{ .Version }}-arm64v8

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
