---
aws:
  # Metrics specifies which metrics to fetch
  metrics:
  #  - name: daily_cost
  #    granularity: daily
  #    metrics:
  #      - "NetAmortizedCost"
  #      - "NetUnblendedCost"
  #    group_by:
  #      - type: DIMENSION
  #        key: SERVICE
  #    filter:
  #      dimensions:
  #        key: SERVICE
  #        values: ["CloudWatch", "EC2 - Other", "DynamoDB"]
    - granularity: daily
      metrics:
        - "NetAmortizedCost"
        - "NetUnblendedCost"
      group_by:
        - type: DIMENSION
          key: SERVICE
      filter:
        dimensions:
          key: SERVICE
          values: ["AWS Cost Explorer"]
    - granularity: daily
      metrics:
        - "NetAmortizedCost"
        - "NetUnblendedCost"
      group_by:
        - type: DIMENSION
          key: SERVICE

outputs:
  - type: "http"
    converter: "prometheus"
