{{- with .Values.serviceAccount }}
{{- if .create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cost-exporter.serviceAccountName" $ }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ required "AWS Role ARN is required" .awsRoleArn }}"
{{- end }}
{{- end }}
