---
name: Unit Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'charts/**/*'
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths-ignore:
      - '**.md'
      - 'charts/**/*'

permissions: read-all
jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.8'
      - name: Install Richgo
        run: |
          go install github.com/kyoh86/richgo@latest

      - name: Run Tests
        run: |
          #!/bin/bash
          set -e
          set -x
          go mod tidy
          richgo test -v ./...
